### ISSUE TITLE
Programmatic api?

### ISSUE THREAD

**Issue by NerdDiffer** [CodeDotJS/kote#1]
Hello,

Are there any plans of creating a programmatic API for this module?
For example:

```js
var kote = require('kote');

kote.goodReads(function(err, quote) {
  console.log(quote);
});
```

**Comment by CodeDotJS** [comment]
Hi @NerdDiffer 

Saw the issue before few hours. So yeah, here it is - [kote-api](https://github.com/CodeDotJS/kote-api)

Example : 

``` js
const kote = require('kote-api');

kote.goodReads().then(quote => {
    console.log(quote);
});
```

Thanks for the suggestion. :)
